title: Pediatric Urology Book
author: Arlen AM, Gundeti MS, López P-J, Rove KO
email: editors@pediatricurologybook.com
tagline: A free online book of Pediatric Urology
description: This free, online book of Pediatric Urology, Edition 2.0, features frequently-updated topics such as management of hydronephrosis, hypospadias techniques, approaches to urinary tract infection, information about bowel and bladder dysfunction, neurogenic bladder, pediatric urologic oncology, and much more.
baseurl: ""
url: "https://beta.pediatricurologybook.com"
twitter_username: PedUrologyBook
mastodon_username: pediatricurologybook
github_username: kylerove/pediatricurologybook
youtube_username: pediatricurologybook
repository: kylerove/pediatricurologybook
permalink: pretty
img: /img/logo.png
env: development
encoding: utf-8
theme: null
version: 2.0.0
timezone: America/Denver

# Build settings
plugins:
  - jekyll-minifier
  - jekyll-polyglot
  - jekyll-toc
  - jekyll-timeago
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-scholar
  - liquid_reading_time
  - liquid_pluralize

# Sitemap settings
defaults:
  -
    scope:
      path:            "assets/ajax/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/csl/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/css/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/figures/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/fonts/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/js/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/pdfs/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/site-img/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/vendor/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "assets/fonts/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "_r/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "book/*"
    values:
      js:              /assets/js/pages/chapter.js

# Language / Polyglot settings
languages: ["en","es","zh","pt"]
default_lang: "en"
languages-captions: 
  - 
    caption: English
    language: en
    icon: fa-globe-americas
  - 
    caption: Español
    language: es
    icon: fa-globe-americas
  - 
    caption: 简体中文
    language: zh
    icon: fa-globe-asia
  - 
    caption: Português
    language: pt
    icon: fa-globe-europe
exclude_from_localization: ["_r", "_config.yml", "assets", "_layouts", "_includes", "_data", "_references", "_plugin", "README.md", "LICENSE"]
parallel_localization: false

# Chapters
collections:
  chapters:
    output: true
    sections: true
    sort_by: sort-key
    permalink: /book/chapters/:title/

# Jekyll Spaceship
jekyll-spaceship:
  processors:
    - video-processor
  video-processor:
    default:
      id: 'video-{id}'
      class: 'video'
      width: '100%'
      height: 350
      border: 0
      style: 'max-width: 600px'
      allow: 'encrypted-media; picture-in-picture'

# Table of contents settings
toc:
  min_level: 2
  max_level: 5
  list_class: "nav nav-list flex-column mb-5"
  item_class: "nav-item"

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# Figure settings
figures:
  dir: /figures
  enumerate: true
  analytics: false

# Reference / Scholar settings
scholar:
  style: ./assets/csl/pub-exp.csl
  bibliography_template: bib
  locale: en
  source: ./_references
  allow_locale_overrides: true
  cite_class: citation
  
# Exclude from processing
exclude:
  - .git/
  - .git_ignore
  - .jekyll-cache/
  - .ruby-version
  - .sass-cache/
  - gemfiles/
  - _r/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md